spring.application.name=settleUp

server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/settleup
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin


jwt.secret= mySuperSecretKeyForSettleUpApplication123456789
jwt.expiration=86400000